# Generated by Django 3.1.12 on 2022-02-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200706_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfilepath',
            name='path',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
